name: js_video_vision_models
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.4.0=py312h06a4308_0
  - aiohttp=3.10.5=py312h5eee18b_0
  - aiohttp-cors=0.7.0=pyhd8ed1ab_2
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alembic=1.14.1=pyhd8ed1ab_0
  - alsa-lib=1.2.12=h4ab18f5_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=py312h06a4308_0
  - aws-c-auth=0.7.31=h57bd9a3_0
  - aws-c-cal=0.7.4=hfd43aa1_1
  - aws-c-common=0.9.28=hb9d3cd8_0
  - aws-c-compression=0.2.19=h756ea98_1
  - aws-c-event-stream=0.4.3=h29ce20c_2
  - aws-c-http=0.8.10=h5e77a74_0
  - aws-c-io=0.14.18=h33ff4e5_10
  - aws-c-mqtt=0.10.6=h02abb05_0
  - aws-c-s3=0.6.6=h834ce55_0
  - aws-c-sdkutils=0.1.19=h756ea98_3
  - aws-checksums=0.1.20=h756ea98_0
  - aws-crt-cpp=0.28.3=h469002c_5
  - aws-sdk-cpp=1.11.407=h9f1560d_0
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.8.0=hd126650_2
  - azure-storage-blobs-cpp=12.12.0=hd2e3451_0
  - azure-storage-common-cpp=12.7.0=h10ac4d7_1
  - azure-storage-files-datalake-cpp=12.11.0=h325d260_1
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2025.6.15=py312h06a4308_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorful=0.5.6=pyhd8ed1ab_0
  - colorlog=6.9.0=pyh707e725_1
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312h68727a3_2
  - coreforecast=0.0.15=py312h68727a3_1
  - cryptography=44.0.1=py312hda17c39_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - datasets=2.19.1=py312h06a4308_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.6=py312h2ec8cdc_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.8=py312h06a4308_0
  - distlib=0.3.9=pyhd8ed1ab_1
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - double-conversion=3.3.0=h59595ed_0
  - einops=0.8.0=pyhd8ed1ab_0
  - elfutils=0.191=h924a536_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=6.1.2=gpl_h8657690_705
  - filelock=3.13.1=py312h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py312h66e93f0_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.0=py312h5eee18b_0
  - fsspec=2024.3.1=py312h06a4308_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gflags=2.2.2=h6a678d5_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py312h06a4308_0
  - glib=2.82.1=h2ff4ddf_0
  - glib-tools=2.82.1=h4833e2c_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h5746830_0
  - google-api-core=2.24.1=pyhd8ed1ab_0
  - google-auth=2.38.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.68.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.1.1=py312h2ec8cdc_1
  - grpcio=1.62.2=py312hb06c811_0
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - huggingface_hub=0.30.2=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - jasper=4.2.4=h536e39c_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libarrow=17.0.0=had3b6fe_16_cpu
  - libarrow-acero=17.0.0=h5888daf_16_cpu
  - libarrow-dataset=17.0.0=h5888daf_16_cpu
  - libarrow-substrait=17.0.0=hf54134d_16_cpu
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp19.1=19.1.0=default_hb5137d0_0
  - libclang13=19.1.0=default_h9c6a7e4_0
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.7.68=0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.21=h4bc722e_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.82.1=h2ff4ddf_0
  - libglu=9.0.0=ha6d2627_1004
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=14.1.0=h77fa898_1
  - libgoogle-cloud=2.29.0=h435de7b_0
  - libgoogle-cloud-storage=2.29.0=h0121fbd_0
  - libgpg-error=1.50=h4f305b6_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm19=19.1.0=ha7bfdaf_0
  - libmicrohttpd=1.0.1=hbc5bc17_1
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopencv=4.10.0=qt6_py312h54e5bfc_606
  - libopenvino=2024.4.0=hac27bb2_0
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_0
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_0
  - libopenvino-onnx-frontend=2024.4.0=h56242b0_0
  - libopenvino-paddle-frontend=2024.4.0=h56242b0_0
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_0
  - libopenvino-tensorflow-frontend=2024.4.0=h358ae18_0
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_0
  - libopus=1.3.1=h7f98852_1
  - libparquet=17.0.0=h39682fd_16_cpu
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=16.4=h2d7952a_2
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libsystemd0=256.6=h2774228_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libthrift=0.20.0=h0e7cc3e_1
  - libtiff=4.7.0=h6565414_0
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.6.2=h9c3ff4c_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - lightning-utilities=0.11.9=py312h06a4308_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mako=1.3.9=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.1=py312h7900ff3_1
  - matplotlib-base=3.9.1=py312h854627b_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.2=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - memray=1.13.4=py312h991ec20_0
  - mkl=2022.1.0=hc2b9512_224
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=py312h06a4308_0
  - msgpack-python=1.1.0=py312h68727a3_0
  - multidict=6.0.4=py312h5eee18b_0
  - multiprocess=0.70.15=py312h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_1
  - mysql-libs=9.0.1=he0572af_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=py312h06a4308_0
  - neuralforecast=2.0.1=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.105=hd34e28f_0
  - numpy=1.26.4=py312heda63a1_0
  - ocl-icd=2.3.2=hd590300_1
  - opencensus=0.11.3=pyhd8ed1ab_1
  - opencensus-context=0.1.3=py312h7900ff3_3
  - opencv=4.10.0=qt6_py312hac6a15e_606
  - openexr=3.2.2=h04e0de5_2
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.1=h7b32b05_0
  - optuna=4.2.1=pyhd8ed1ab_0
  - orc=2.0.2=h669347b_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=1.0.1=py312h06a4308_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h56024de_1
  - pip=24.2=py312h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - proto-plus=1.26.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py312h83439f5_1
  - psutil=6.0.0=py312h66e93f0_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.10.0=qt6_py312h071dcc1_606
  - py-spy=0.4.0=h4c5a871_1
  - pyarrow=17.0.0=py312h9cebb41_1
  - pyarrow-core=17.0.0=py312h9cafe31_1_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.10.6=pyh3cfb1c2_0
  - pydantic-core=2.27.2=py312h12e396e_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyopenssl=25.0.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py312h5eee18b_1
  - python_abi=3.12=5_cp312
  - pytorch=2.4.0=py3.12_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.5.0.post0=pyh101cb37_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywavelets=1.8.0=py312h5eee18b_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=26.2.0=py312hbf22597_2
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h3155989_26
  - qt6-main=6.7.3=h20baabe_0
  - ray-core=2.37.0=py312h3baf6f4_0
  - ray-default=2.37.0=py312h6dd12e9_0
  - ray-tune=2.37.0=py312h7900ff3_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - referencing=0.36.2=pyh29332c3_0
  - regex=2024.9.11=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.23.1=py312h3b7be25_0
  - rsa=4.9=pyhd8ed1ab_1
  - s2n=1.5.3=h7b32b05_0
  - safetensors=0.4.4=py312hb7cc22b_0
  - scikit-learn=1.5.2=py312h7a48858_1
  - scipy=1.14.1=py312h7d485d2_0
  - sentry-sdk=2.18.0=py312h06a4308_0
  - setproctitle=1.3.5=py312h66e93f0_0
  - setuptools=75.1.0=py312h06a4308_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=7.1.0=pyhd8ed1ab_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=ha2e4443_0
  - sqlalchemy=2.0.38=py312h66e93f0_0
  - sqlite=3.32.3=hcee41ef_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312h5eee18b_0
  - svt-av1=2.2.1=h5888daf_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.13.0=h84d6215_0
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - textual=2.1.1=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.21.0=py312h8360d73_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.4.0=py312_cu121
  - torchmetrics=1.7.1=pyhd8ed1ab_0
  - torchtriton=3.0.0=py312
  - torchvision=0.19.0=py312_cu121
  - tornado=6.4.1=py312h66e93f0_1
  - tqdm=4.66.5=py312he106c6f_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - transformers=4.51.3=pyhd8ed1ab_0
  - typing=3.10.0.0=py312h06a4308_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - urllib3=2.2.2=py312h06a4308_0
  - utilsforecast=0.2.11=pyhd8ed1ab_0
  - virtualenv=20.29.2=pyhd8ed1ab_0
  - wandb=0.19.10=py312h12e396e_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py312h06a4308_0
  - wrapt=1.17.2=py312h66e93f0_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.3=hb9d3cd8_2
  - xorg-libxext=1.3.4=hb9d3cd8_3
  - xorg-libxfixes=6.0.0=hb9d3cd8_1
  - xorg-libxi=1.7.10=hb9d3cd8_2
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxtst=1.2.5=hb9d3cd8_1
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1003
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py312h5eee18b_0
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - h5py==3.14.0
      - huggingface-hub==0.29.1
      - lazy-loader==0.4
      - mne==1.9.0
      - pooch==1.8.2
      - ptwt==0.1.9
      - pymatreader==1.0.0
      - xmltodict==0.14.2
